# Generated by Django 5.2.16 on 2026-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=50)),
                ('simbolo', models.CharField(blank=True, default='', max_length=10)),
                ('tasa', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Gs por 1 unidad')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'db_table': 'caja_tasas_cambio',
            },
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='tasas_aplicadas',
            field=models.JSONField(blank=True, null=True, verbose_name='Tasas usadas en el arqueo'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='totales_por_moneda',
            field=models.JSONField(blank=True, null=True, verbose_name='Conteo físico por moneda'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tasa_usada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tasa de cambio usada (Gs por 1 unidad)'),
        ),
    ]
