# Generated by Django 5.2.16 on 2026-09-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_tasacambio_cortecaja_tasas_aplicadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto'),
        ),
    ]
