# Generated by Django 5.2.16 on 2026-08-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_configuracion_csc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='ambiente_sifen',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='cCiuEmi',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='cDepEmi',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='cDirEmi',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='certificado_pkcs12',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='csc',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='csc_id',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='csc_pin',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='dDesCiuEmi',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='dDesDepEmi',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='dEmailE',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='dNumCas',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='gActEco_codigo',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='gActEco_descripcion',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='sifen_habilitado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cdc',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='kude',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='qr_base64',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='sifen_estado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='sifen_mensaje',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='xml',
        ),
    ]
