# Generated by Django 6.1 on 2026-08-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_remove_configuracion_ambiente_sifen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='actividades_economicas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ambiente_sifen',
            field=models.CharField(choices=[('test', 'Test'), ('prod', 'Producción')], default='test', max_length=4),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ciudad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ciudad_descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='csc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='csc_id',
            field=models.CharField(default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='departamento',
            field=models.PositiveSmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='departamento_descripcion',
            field=models.CharField(default='ALTO PARANA', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='distrito',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='distrito_descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ruta_certificado',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tipo_contribuyente',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tipo_regimen',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='factura',
            name='cdc',
            field=models.CharField(blank=True, max_length=44),
        ),
        migrations.AddField(
            model_name='factura',
            name='establecimiento',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_lote',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='factura',
            name='observacion_sifen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='punto_expedicion',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_firmado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_envio', 'Pendiente de envío'), ('en_espera', 'En espera de resultado SET'), ('generada', 'Generada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
    ]
