# Generated by Django 5.2.16 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Ingredientes del plato (visible en la carta digital)', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas / recomendaciones de servicio (visible en la carta digital)', null=True),
        ),
    ]